import "../styles/globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

import { Inter } from "next/font/google";
import SessionProvider from "@/components/SessionProvider";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <>
            <NavBar />
          </>
          {children}
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
